# Generated by Django 4.0.4 on 2022-04-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
    ]
